version: "1.0"
name: pipeline-deploy
displayName: 构建并部署
stages:
- name: Docker 镜像构建
  displayName: Docker 镜像构建
  strategy: naturally
  trigger: auto
  executor: []
  steps:
  - step: build@docker
    name: build_docker
    displayName: 镜像构建
    type: account
    repository: ccr.ccs.tencentyun.com
    username: "${TCR_USERNAME}"
    password: "${TCR_PASSWORD}"
    tag: lqzzql/web:latest
    dockerfile: ./Dockerfile
    context: ""
    artifacts: []
    isCache: true
    processorType:
    - amd64
    parameter: {}
    notify: []
    strategy:
      retry: "0"
- name: 部署到服务器
  displayName: 部署到服务器
  strategy: naturally
  trigger: auto
  executor: []
  steps:
  - step: shell@agent
    name: deploy_shell
    displayName: Shell 脚本执行
    script: |-
      cd /home/ubuntu/个人网站
      docker login ccr.ccs.tencentyun.com -u ${TCR_USERNAME} -p ${TCR_PASSWORD}
      docker compose pull web
      docker compose up -d web
      docker image prune -f
    hostGroupID:
      ID: tencent-cloud
      hostID:
      - b57ee737-9ddd-4dba-bda2-0322378ea9f2
    notify: []
    strategy:
      retry: "0"
triggers:
  trigger: auto
  push:
    branches:
      prefix: []
      precise:
      - main
      include: []
notify: []
variables:
  global:
  - TCR_USERNAME
  - TCR_PASSWORD
